name: fire_chat
description: This is a Firebase-based chat room
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  sqflite: 
  path:
  flutter_bloc:
  intl: ^0.18.0
  # flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/fire.png"
# flutter_launcher_icons:
#   path: ../..   

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/fire.png"
  image_path_ios: "assets/images/fire.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/fire.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/fire.png" # only available for Android 8.0 devices and above
  min_sdk_android: 16 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  # web:
  #   generate: true
  #   image_path: "assets/images/fire.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "assets/images/fire.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "assets/images/fire.png"

flutter:
  uses-material-design: true


