// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClV4eOtJT31CRhr9HRoOUAYfNh1c4TwCw',
    appId: '1:77711489802:web:1e27925c87d101115218f3',
    messagingSenderId: '77711489802',
    projectId: 'fir-cloudfunction-40461',
    authDomain: 'fir-cloudfunction-40461.firebaseapp.com',
    storageBucket: 'fir-cloudfunction-40461.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrIojn_jE4HBMQ0t5ljNlQOyks9SCaXAs',
    appId: '1:77711489802:android:9aaa62805e125b355218f3',
    messagingSenderId: '77711489802',
    projectId: 'fir-cloudfunction-40461',
    storageBucket: 'fir-cloudfunction-40461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYdyBR4z5Hzrofhw7okycFDERH2r0IZYA',
    appId: '1:77711489802:ios:4e775e2989703e5d5218f3',
    messagingSenderId: '77711489802',
    projectId: 'fir-cloudfunction-40461',
    storageBucket: 'fir-cloudfunction-40461.appspot.com',
    iosClientId: '77711489802-n92oh9bnat76mh3qne6lq0ejgvfa4306.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYdyBR4z5Hzrofhw7okycFDERH2r0IZYA',
    appId: '1:77711489802:ios:4e775e2989703e5d5218f3',
    messagingSenderId: '77711489802',
    projectId: 'fir-cloudfunction-40461',
    storageBucket: 'fir-cloudfunction-40461.appspot.com',
    iosClientId: '77711489802-n92oh9bnat76mh3qne6lq0ejgvfa4306.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireChat',
  );
}
